from sqlalchemy import Column, ForeignKey, Integer, BigInteger, String, DateTime, Boolean, Float, Date, Text, Time
from sqlalchemy.ext.declarative import declared_attr
from datetime import datetime, date
from sqlalchemy.orm import relationship
from core.session import Base as Basex

class Base(Basex):
    __abstract__ = True

    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()

# Create DataTable for User details
class User(Base):
    id = Column(Integer, primary_key=True, index=True)
    customerName= Column(String(500), default=None)
    companyName= Column(String(500), default=None)
    gstNo= Column(String(500), default=None)
    email = Column(String(500), unique=True, default=None)
    mobile = Column(BigInteger, unique=True, default=None)
    password = Column(String(500), default=None)
    branchName = Column(String(500), default=None)
    status = Column(Boolean(), default=True)
    verified = Column(Boolean(), default=False)
    subscription_end = Column(DateTime, default=None)
    admin = Column(Boolean(), default=None)
    staff = Column(Boolean(), default=None)
    created = Column(DateTime, default=datetime.now())
    updated = Column(DateTime, default=datetime.now())
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)
    permissions = relationship("UserPermission", back_populates="owner")
    place = relationship("PlaceDetails", back_populates="owner")
    floor = relationship("FloorDetails", back_populates="owner")
    category = relationship("CategoryDetails", back_populates="owner")
    category_wise_slots = relationship("CategoryWiseSlots", back_populates="owner")
    clubs = relationship("ClubDetails", back_populates="owner")
    club_transaction = relationship("ClubTransactionDetails", back_populates="owner")
    migration = relationship("MigrationDetails", back_populates="owner")
    role = relationship("RoleDetails", back_populates="owner")
    role_user = relationship("RoleUserDetails", back_populates="owner")
    country = relationship("CountryDetails", back_populates="owner")
    parking = relationship("ParkingDetails", back_populates="owner")
    tariff = relationship("TariffDetails", back_populates="owner")
    vehicleAmount = relationship("VehicleAmountDetails", back_populates="owner")

class UserPermission(Base):
    id = Column(Integer, primary_key=True, index=True)
    designation = Column(String(500), default=None)
    places = Column(Boolean, default=True)
    floors = Column(Boolean, default=True)
    category = Column(Boolean, default=True)
    categoryWiseSlots = Column(Boolean, default=True)
    clubs = Column(Boolean, default=True)
    clubTransaction = Column(Boolean, default=True)
    rfdVehicles = Column(Boolean, default=True)
    tariff = Column(Boolean, default=True)
    migrations = Column(Boolean, default=True)
    parking = Column(Boolean, default=True)
    countries = Column(Boolean, default=False)
    language = Column(Boolean, default=False)
    roles = Column(Boolean, default=False)
    roleUser = Column(Boolean, default=False)
    vehicleAmount = Column(Boolean, default=False)
    passwordReset = Column(Boolean, default=False)
    user_id = Column(Integer, ForeignKey("user.id"))
    updated = Column(DateTime, default=datetime.now())
    owner = relationship("User", back_populates="permissions")

class OTP(Base):
    id = Column(Integer, primary_key=True, index=True)
    otp_email = Column(Integer, default=123456)
    email_verified = Column(Boolean(), default=False)
    otp_mobile = Column(Integer, default=123456)
    mobile_verified = Column(Boolean(), default=False)
    email_otp_created = Column(DateTime, default=datetime.now())
    mobile_otp_created = Column(DateTime, default=datetime.now())
    othersOTP = Column(String(500), default="")
    user_id = Column(Integer, ForeignKey("user.id"))
    

# Create DataTable for password reset
class password_reset(Base):
    id = Column(Integer, primary_key=True, index=True)
    user_email_id = Column(String(500), nullable=False, unique=True)
    othersPassReset = Column(String(500), default="")
    otp = Column(Integer)    

    
class PlaceDetails(Base):
    id = Column(Integer, primary_key=True, index=True)
    placeName = Column(String(500), default=None)
    description = Column(Text, default=None)
    status = Column(Integer, default=None)
    created_by = Column(Integer, default=None)
    modified_by = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now(), onupdate=datetime.now())
    owner = relationship("User", back_populates="place")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)
    

class FloorDetails(Base):
    id = Column(Integer, primary_key=True, index=True) 
    place_id = Column(Integer, default=None)
    floorName = Column(String(500), default=None)
    floorLevel = Column(Integer, default=None)
    remarks = Column(String(500), default=None)
    status = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now(), onupdate=datetime.now())
    owner = relationship("User", back_populates="floor")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class CategoryDetails(Base):
    id = Column(Integer, primary_key=True, index=True) 
    place_id = Column(Integer, default=None)
    type = Column(String(500), default=None)
    description = Column(String(500), default=None)
    limitCount = Column(Integer, default=None)
    status = Column(Integer, default=None)
    created_by = Column(Integer, default=None)
    modified_by = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    owner = relationship("User", back_populates="category")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class CategoryWiseSlots(Base):
    id = Column(Integer, primary_key=True, index=True) 
    place_id = Column(Integer, default=None)
    floor_id = Column(Integer, default=None)
    category_id = Column(Integer, default=None)
    slotName = Column(String(500), default=None)
    slotID = Column(Integer, default=None)
    identity = Column(String(500), default=None)
    remarks = Column(Text, default=None)
    status = Column(Integer, default=None)
    created_id = Column(Integer, default=None)
    updated_id = Column(Integer, default=None)
    created_by = Column(Integer, default=None)
    updated_by = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now(), onupdate=datetime.now())
    owner = relationship("User", back_populates="category_wise_slots")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class ClubDetails(Base):
    id = Column(Integer, primary_key=True, index=True)  
    clubName = Column(String(500), default=None)
    vehicleNumber = Column(Integer, default=None)
    storeNumber = Column(Integer, default=None)
    vehicleType = Column(Integer, default=None)
    cronJobDate = Column(DateTime, default=None)
    cronJobStatus = Column(Integer, default=None)
    owner = relationship("User", back_populates="clubs")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)


class ClubTransactionDetails(Base):   
    id = Column(Integer, primary_key=True, index=True) 
    club_id = Column(Integer, default=None)
    transaction_id = Column(Integer, default=None)
    amount = Column(Float, default=None)
    gracePeriod = Column(Integer, default=None)
    cronJobDate = Column(DateTime, default=None)
    cronJobStatus = Column(Integer, default=None)
    created_by = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    owner = relationship("User", back_populates="club_transaction")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class MigrationDetails (Base):
    id = Column(Integer, primary_key=True, index=True) 
    migration = Column(String(500), default=None)
    batch = Column(Integer, default=None)
    owner = relationship("User", back_populates="migration")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class RoleDetails(Base):
    id = Column(Integer, primary_key=True, index=True)  
    roleName = Column(String(500), default=None)
    description = Column(String(500), default=None)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now())
    owner = relationship("User", back_populates="role")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class RoleUserDetails(Base):
    id = Column(Integer, primary_key=True, index=True)  
    role_id = Column(Integer, default=None)
    user_id = Column(Integer, ForeignKey("user.id"))
    owner = relationship("User", back_populates="role_user")
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class CountryDetails(Base):
    id = Column(Integer, primary_key=True, index=True)    
    countryName = Column(String(500), default=None)
    countryCode = Column(String(500), default=None)
    status = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now(), onupdate=datetime.now())
    user_id = Column(Integer, ForeignKey("user.id"))
    owner = relationship("User", back_populates="country")
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)

class ParkingDetails(Base):
    id = Column(Integer, primary_key=True, index=True)  
    place_id = Column(Integer, default=None)
    slot_id = Column(Integer, default=None)
    slotId = Column(Integer, default=None)
    category_id = Column(Integer, default=None)
    barcode = Column(Integer, default=None)
    vehicle_no = Column(String(500), default=None)
    club_type = Column(String(500), default=None)
    rfid_no = Column(String(500), default=None)
    driver_name = Column(String(500), default=None)
    driver_mobile = Column(String(500), default=None)
    inTime = Column(DateTime, default=datetime.now())
    outTime = Column(DateTime, default=datetime.now())
    exitFloorId = Column(Integer, default=None)
    amount = Column(Float, default=None)
    isPaid = Column(Float, default=None)
    paid = Column(Float, default=None)
    status = Column(Integer, default=None)
    created_by = Column(Integer, default=None)
    updated_by = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now(), onupdate=datetime.now())
    user_id = Column(Integer, ForeignKey("user.id"))
    owner = relationship("User", back_populates="parking")
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)


class TariffDetails(Base):
    id = Column(Integer, primary_key=True, index=True)  
    place_id = Column(Integer, default=None)  
    tariffName = Column(String(500), default=None)
    startDate = Column(DateTime, default=datetime.now())
    endDate = Column(DateTime, default=datetime.now())
    minAmount = Column(Float, default=None)
    parHour = Column(Float, default=None)
    status = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, default=datetime.now(), onupdate=datetime.now())
    user_id = Column(Integer, ForeignKey("user.id"))
    owner = relationship("User", back_populates="tariff")
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)


class VehicleAmountDetails(Base):
    id = Column(Integer, primary_key=True, index=True) 
    rateName = Column(String(500), default=None)
    vehicleCategory = Column(String(500), default=None)
    type = Column(String(500), default=None)
    category = Column(String(500), default=None)
    rate = Column(Float, default=None)
    setTime = Column(String(500), default=None)
    status = Column(Integer, default=None)
    created_by = Column(Integer, default=None)
    modified_by = Column(Integer, default=None)
    created_at = Column(DateTime, default=datetime.now())
    owner = relationship("User", back_populates="vehicleAmount")
    user_id = Column(Integer, ForeignKey("user.id"))
    headOfficeID = Column(Integer, default=None)
    branchID = Column(Integer, default=None)
    level = Column(Integer, default=None)    